package com.project.ui;

import java.io.IOException;
import java.util.Map;

import com.informedsearchalgorithms.astarsearchalgorithm.algorithm.AStarSearchAlgorithm;
import com.informedsearchalgorithms.greedybestfirstsearchalgorithm.algorithm.GreedyBestFirstSearchAlgorithm;
import com.informedsearchalgorithms.nodesQueuesComparators.HeuristicWeightedNode;
import com.uninformedsearchalgorithms.nodesQueuesComparators.WeightedNode;
import com.uninformedsearchalgorithms.uniformcostsearchalgorithm.algorithm.UniformCostSearchAlgorithm;

public class DefineGraphHeuristic extends javax.swing.JFrame {

    /**
     * Creates new form DefineGraph
     */
	
	String GBFSOrAS;
	
    public DefineGraphHeuristic(String GBFSOrAS) {
        initComponents();
        
        // Loading the previous given data
        nodeTF.setText(UI.allNodes);
        childrenGroupTF.setText(UI.allNeighbourgroups);
        costTF.setText(UI.allcostGroups);
        goalStateTF.setText(UI.goalState);
        heuristicCostTF.setText(UI.allHeuristicCosts);
        
     // Use to Specifiy either algorithm is GBFS or AS
        this.GBFSOrAS = GBFSOrAS;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                            
    private void initComponents() {

    	jPanel1 = new javax.swing.JPanel();
        nodeLbl = new javax.swing.JLabel();
        nodeTF = new javax.swing.JTextField();
        egNodeLbl = new javax.swing.JLabel();
        childrenGroupsLbl1 = new javax.swing.JLabel();
        childrenGroupTF = new javax.swing.JTextField();
        egChildLbl = new javax.swing.JLabel();
        costLbl = new javax.swing.JLabel();
        costTF = new javax.swing.JTextField();
        egNodeLbl2 = new javax.swing.JLabel();
        egNeighbour2Lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        heuristicCostTF = new javax.swing.JTextField();
        goalStateTF = new javax.swing.JTextField();
        goalStateLbl = new javax.swing.JLabel();
        egNodeLbl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subButton = new javax.swing.JButton();
        informationJBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nodeLbl.setText("Enter Node");

        egNodeLbl.setText("Seperate nodes by space e.g. A B C .....");

        childrenGroupsLbl1.setText("Neighbours");

        egChildLbl.setText("Seperate each group of neighbours by a comma & within group ");

        costLbl.setText("Enter Cost");

        egNodeLbl2.setText("Format should be same as defined in neighbours");

        egNeighbour2Lbl.setText("seperate by space e.g. A,B C,D,E ......");

        jLabel2.setText("Heuristic Cost");

        goalStateLbl.setText("Goal State");

        egNodeLbl3.setText("Format should be same as defined in neighbours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(egNeighbour2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(egChildLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(childrenGroupsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(childrenGroupTF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nodeTF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heuristicCostTF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(egNodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(egNodeLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(goalStateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(goalStateTF)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(egNodeLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(egNodeLbl)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(childrenGroupsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(childrenGroupTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(egChildLbl)
                .addGap(4, 4, 4)
                .addComponent(egNeighbour2Lbl)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(egNodeLbl2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(heuristicCostTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(egNodeLbl3)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goalStateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goalStateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Define Graph");

        subButton.setText("Submit");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        informationJBtn.setText("i");

        informationJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationJBtnActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(informationJBtn)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informationJBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        
        setLocationRelativeTo(null);
        
    }                      

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {        
    	
    	// Updating the List of Nodes and List of NeighbourGroups with latest values
    	UI.allNodes = nodeTF.getText().trim();
    	UI.allNeighbourgroups = childrenGroupTF.getText().trim();
    	UI.goalState = goalStateTF.getText();
    	UI.allcostGroups = costTF.getText().trim();
    	UI.allHeuristicCosts = heuristicCostTF.getText().trim();
    	
    	// Creating the Window of operation based on List of Selected Algorithms
    	UI.createWindow(UI.selectedAlgorithmsList);
    	
    	// Add Children to Nodes
    	Map<String, HeuristicWeightedNode> children = UI.setChildrenAndCostAndHeuristciCost(UI.getNodesListOfHeuristicWeightedNode(UI.getNodesListOfString(UI.allNodes)), UI.allNeighbourgroups, UI.getNodesListOfString(UI.allNodes), costTF.getText().trim(), UI.allHeuristicCosts);
    	
		// Display Result in Dialogue Box	    	
		if(GBFSOrAS.equalsIgnoreCase("GBFS")) {
			UI.displayResult(GreedyBestFirstSearchAlgorithm.search(children.get(UI.getNodesListOfString(UI.allNodes)[0]), UI.goalState));	
			
		}
		else {
			
			UI.displayResult(AStarSearchAlgorithm.search(children.get(UI.getNodesListOfString(UI.allNodes)[0]), UI.goalState));
		}
		
    }                                             

    private void informationJBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	
    	String url = "https://github.com/AhsanRaza05/Search-Algorithms-in-Artificial-Intelligence-Java/blob/main/README.md#ASS_Head";
    	
    	if(GBFSOrAS.equalsIgnoreCase("GBFS")) {
    		
    		url = "https://github.com/AhsanRaza05/Search-Algorithms-in-Artificial-Intelligence-Java/blob/main/README.md#GBFS_Head";
    	}
    	
    	try {
			java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }   
 
    // Variables declaration - do not modify                     
    private javax.swing.JTextField childrenGroupTF;
    private javax.swing.JLabel childrenGroupsLbl1;
    private javax.swing.JLabel costLbl;
    private javax.swing.JTextField costTF;
    private javax.swing.JLabel egChildLbl;
    private javax.swing.JLabel egNeighbour2Lbl;
    private javax.swing.JLabel egNodeLbl;
    private javax.swing.JLabel egNodeLbl2;
    private javax.swing.JLabel egNodeLbl3;
    private javax.swing.JLabel goalStateLbl;
    private javax.swing.JTextField goalStateTF;
    private javax.swing.JTextField heuristicCostTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nodeLbl;
    private javax.swing.JTextField nodeTF;
    private javax.swing.JButton subButton;
    private javax.swing.JButton informationJBtn;
    // End of variables declaration                   
}
